/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantalla;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class FrmParametrizacion extends javax.swing.JFrame {
    private FrmMenuPrincipal myMenu;

    /**
     * Creates new form FrmParametrizacion
     */
    public FrmParametrizacion(FrmMenuPrincipal menu) {
        initComponents();
        
        this.myMenu = menu;
        this.setLocationRelativeTo(null);
        llenarTablaRutas();
        llenarTablaBuses();
        llenarTablaSalidas();
        cargarCombosBuses();
        cargarCombosSalidas();
        cargarCombosDestinos();
    }
  /*   private Empresa getEmpresa() {
        return myMenu.getApertura().getMyEmpresa();
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelBuses = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBuses = new javax.swing.JTable();
        panelAbajoBuses = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        u1 = new javax.swing.JLabel();
        txtPlacaBus = new javax.swing.JTextField();
        m1 = new javax.swing.JLabel();
        cmdAnadirBus = new javax.swing.JButton();
        comboTipoServicioBus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        panelXBuses = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbPlacas = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbNuevoEstado = new javax.swing.JComboBox<>();
        cmdActualizarBus = new javax.swing.JButton();
        panelSalidas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaSalidas = new javax.swing.JTable();
        PanelAbajoSalidas = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        m2 = new javax.swing.JLabel();
        cmdAnadirSalida = new javax.swing.JButton();
        g2 = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        u2 = new javax.swing.JLabel();
        comboRutaSalida = new javax.swing.JComboBox<>();
        comboBusSalida = new javax.swing.JComboBox<>();
        calendarFechaSalida = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelXSalidas = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cmbActualizarSalidas = new javax.swing.JButton();
        panelRutasPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRutas = new javax.swing.JTable();
        panelAbajoRuta = new javax.swing.JPanel();
        panelFormularioRutas = new javax.swing.JPanel();
        g = new javax.swing.JLabel();
        u = new javax.swing.JLabel();
        txtTiempoEst = new javax.swing.JTextField();
        m = new javax.swing.JLabel();
        txtTarifaBase = new javax.swing.JTextField();
        btnAnadirRuta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbDestino = new javax.swing.JComboBox<>();
        panelXRuta = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDestinoN = new javax.swing.JTextField();
        txtNuevaTarifa = new javax.swing.JTextField();
        cmdActualizarRuta = new javax.swing.JButton();
        cmbDestinoN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbRutacg = new javax.swing.JComboBox<>();
        panelMensaje = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMensajes = new javax.swing.JTextArea();

        jLabel4.setText("jLabel4");

        jButton2.setText("jButton2");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametrizacion del Sistema");
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jTabbedPane2.setPreferredSize(new java.awt.Dimension(966, 100));

        panelBuses.setLayout(new java.awt.BorderLayout());

        tablaBuses.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        tablaBuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Placa", "Capacidad", "Estado"
            }
        ));
        jScrollPane2.setViewportView(tablaBuses);

        panelBuses.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelAbajoBuses.setLayout(new javax.swing.BoxLayout(panelAbajoBuses, javax.swing.BoxLayout.Y_AXIS));

        u1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        u1.setText("placa");

        txtPlacaBus.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N

        m1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        m1.setText("tipo de servicio");

        cmdAnadirBus.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        cmdAnadirBus.setText("añadir");
        cmdAnadirBus.addActionListener(this::cmdAnadirBusActionPerformed);

        comboTipoServicioBus.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        comboTipoServicioBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipoServicioBus.addActionListener(this::comboTipoServicioBusActionPerformed);

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel11.setText("creador de buses");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(u1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPlacaBus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(m1)
                        .addGap(18, 18, 18)
                        .addComponent(comboTipoServicioBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(cmdAnadirBus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel11)))
                .addContainerGap(630, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoServicioBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u1)
                    .addComponent(cmdAnadirBus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelAbajoBuses.add(jPanel2);

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel12.setText("Configuracion de buses");

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel13.setText("placa");

        cmbPlacas.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        cmbPlacas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPlacas.addActionListener(this::cmbPlacasActionPerformed);

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel14.setText("estado");

        cmbNuevoEstado.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        cmbNuevoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmdActualizarBus.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        cmdActualizarBus.setText("actualizar");
        cmdActualizarBus.addActionListener(this::cmdActualizarBusActionPerformed);

        javax.swing.GroupLayout panelXBusesLayout = new javax.swing.GroupLayout(panelXBuses);
        panelXBuses.setLayout(panelXBusesLayout);
        panelXBusesLayout.setHorizontalGroup(
            panelXBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXBusesLayout.createSequentialGroup()
                .addGroup(panelXBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelXBusesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel14)
                        .addGap(41, 41, 41)
                        .addComponent(cmbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(cmdActualizarBus))
                    .addGroup(panelXBusesLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel12)))
                .addContainerGap(668, Short.MAX_VALUE))
        );
        panelXBusesLayout.setVerticalGroup(
            panelXBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXBusesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(panelXBusesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdActualizarBus))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelAbajoBuses.add(panelXBuses);

        panelBuses.add(panelAbajoBuses, java.awt.BorderLayout.SOUTH);

        jTabbedPane2.addTab("Buses", panelBuses);

        panelSalidas.setLayout(new java.awt.BorderLayout());

        tablaSalidas.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        tablaSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Ruta", "Bus", "Hora", "Fecha", "Estado", "Precio final", "Asientos"
            }
        ));
        jScrollPane3.setViewportView(tablaSalidas);

        panelSalidas.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        PanelAbajoSalidas.setLayout(new javax.swing.BoxLayout(PanelAbajoSalidas, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setPreferredSize(new java.awt.Dimension(635, 100));

        m2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        m2.setText("BUS");

        cmdAnadirSalida.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        cmdAnadirSalida.setText("añadir");
        cmdAnadirSalida.addActionListener(this::cmdAnadirSalidaActionPerformed);

        g2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        g2.setText("HORA");

        txtHoraSalida.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N

        u2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        u2.setText("RUTA");

        comboRutaSalida.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        comboRutaSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBusSalida.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        comboBusSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel1.setText("Fecha");

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel15.setText("creacion de salidas");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(g2)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(calendarFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(u2)
                        .addGap(18, 18, 18)
                        .addComponent(comboRutaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(m2)
                        .addGap(18, 18, 18)
                        .addComponent(comboBusSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(cmdAnadirSalida))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(jLabel15)))
                .addContainerGap(477, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(g2)
                        .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(u2)
                        .addComponent(comboRutaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m2)
                        .addComponent(comboBusSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdAnadirSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        PanelAbajoSalidas.add(jPanel6);

        panelXSalidas.setMaximumSize(new java.awt.Dimension(32767, 100));
        panelXSalidas.setMinimumSize(new java.awt.Dimension(400, 100));
        panelXSalidas.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel16.setText("CONfiguracion de salidas");

        cmbActualizarSalidas.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        cmbActualizarSalidas.setText("ACTUALIZAR");
        cmbActualizarSalidas.addActionListener(this::cmbActualizarSalidasActionPerformed);

        javax.swing.GroupLayout panelXSalidasLayout = new javax.swing.GroupLayout(panelXSalidas);
        panelXSalidas.setLayout(panelXSalidasLayout);
        panelXSalidasLayout.setHorizontalGroup(
            panelXSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXSalidasLayout.createSequentialGroup()
                .addGroup(panelXSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelXSalidasLayout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel16))
                    .addGroup(panelXSalidasLayout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(cmbActualizarSalidas)))
                .addContainerGap(674, Short.MAX_VALUE))
        );
        panelXSalidasLayout.setVerticalGroup(
            panelXSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXSalidasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(cmbActualizarSalidas)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        PanelAbajoSalidas.add(panelXSalidas);

        panelSalidas.add(PanelAbajoSalidas, java.awt.BorderLayout.SOUTH);

        jTabbedPane2.addTab("Salidas", panelSalidas);

        panelRutasPrincipal.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

        tablaRutas.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        tablaRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Origen", "Destino", "Tiempo Estimado", "Tarifa Base"
            }
        ));
        jScrollPane1.setViewportView(tablaRutas);

        panelRutasPrincipal.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelAbajoRuta.setLayout(new javax.swing.BoxLayout(panelAbajoRuta, javax.swing.BoxLayout.Y_AXIS));

        panelFormularioRutas.setPreferredSize(new java.awt.Dimension(300, 100));

        g.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        g.setText("destino");

        u.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        u.setText("Tiempo estimado");

        txtTiempoEst.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        txtTiempoEst.addActionListener(this::txtTiempoEstActionPerformed);

        m.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        m.setText("tarifa base");

        txtTarifaBase.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N

        btnAnadirRuta.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        btnAnadirRuta.setText("añadir");
        btnAnadirRuta.addActionListener(this::btnAnadirRutaActionPerformed);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel2.setText("Creador de rutas");

        cmbDestino.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDestino.addActionListener(this::cmbDestinoActionPerformed);

        javax.swing.GroupLayout panelFormularioRutasLayout = new javax.swing.GroupLayout(panelFormularioRutas);
        panelFormularioRutas.setLayout(panelFormularioRutasLayout);
        panelFormularioRutasLayout.setHorizontalGroup(
            panelFormularioRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioRutasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(g)
                .addGap(18, 18, 18)
                .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(u)
                .addGap(18, 18, 18)
                .addComponent(txtTiempoEst, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(m)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTarifaBase, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(114, 114, 114)
                .addComponent(btnAnadirRuta)
                .addGap(130, 130, 130))
            .addGroup(panelFormularioRutasLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFormularioRutasLayout.setVerticalGroup(
            panelFormularioRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioRutasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelFormularioRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g)
                    .addComponent(u)
                    .addComponent(txtTiempoEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m)
                    .addComponent(txtTarifaBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnadirRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelAbajoRuta.add(panelFormularioRutas);

        panelXRuta.setMaximumSize(new java.awt.Dimension(32767, 100));
        panelXRuta.setMinimumSize(new java.awt.Dimension(400, 100));
        panelXRuta.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel3.setText("configuarcion rutas");

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel5.setText("destino");

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel6.setText("Nueva tarifa");

        txtDestinoN.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N

        txtNuevaTarifa.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        txtNuevaTarifa.setMinimumSize(new java.awt.Dimension(100, 21));
        txtNuevaTarifa.setPreferredSize(new java.awt.Dimension(100, 21));

        cmdActualizarRuta.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        cmdActualizarRuta.setText("actualizar");
        cmdActualizarRuta.addActionListener(this::cmdActualizarRutaActionPerformed);

        cmbDestinoN.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        cmbDestinoN.setText("Crear");
        cmbDestinoN.addActionListener(this::cmbDestinoNActionPerformed);

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel8.setText("Crear nuevo destino");

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel7.setText("Actualizar tarifa base");

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        jLabel10.setText("Ruta");

        cmbRutacg.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        cmbRutacg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelXRutaLayout = new javax.swing.GroupLayout(panelXRuta);
        panelXRuta.setLayout(panelXRutaLayout);
        panelXRutaLayout.setHorizontalGroup(
            panelXRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXRutaLayout.createSequentialGroup()
                .addGroup(panelXRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelXRutaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelXRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelXRutaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtDestinoN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addComponent(cmbDestinoN)
                        .addGap(184, 184, 184)
                        .addGroup(panelXRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelXRutaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cmbRutacg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtNuevaTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(cmdActualizarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelXRutaLayout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLabel3)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        panelXRutaLayout.setVerticalGroup(
            panelXRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXRutaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelXRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelXRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDestinoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDestinoN)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevaTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdActualizarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbRutacg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        panelAbajoRuta.add(panelXRuta);

        panelRutasPrincipal.add(panelAbajoRuta, java.awt.BorderLayout.SOUTH);

        jTabbedPane2.addTab("Rutas", panelRutasPrincipal);

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1271, Short.MAX_VALUE)
            .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTablaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jScrollPane4.setPreferredSize(new java.awt.Dimension(900, 100));

        txtMensajes.setEditable(false);
        txtMensajes.setColumns(20);
        txtMensajes.setLineWrap(true);
        txtMensajes.setRows(4);
        txtMensajes.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtMensajes);

        javax.swing.GroupLayout panelMensajeLayout = new javax.swing.GroupLayout(panelMensaje);
        panelMensaje.setLayout(panelMensajeLayout);
        panelMensajeLayout.setHorizontalGroup(
            panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMensajeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelMensajeLayout.setVerticalGroup(
            panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
            .addGroup(panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMensajeLayout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAnadirRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirRutaActionPerformed
        try {
        // 1. Validar que los campos no estén vacíos
            if(txtTiempoEst.getText().trim().isEmpty() || cmbDestino.getSelectedItem()==null || txtTarifaBase.getText().trim().isEmpty()){
                mostrarMensaje("INFO","Complete por favor todos los campos.");
                return;
            }
            
            double tar;
            tar = Double.parseDouble(txtTarifaBase.getText().trim());
            if(tar<0){
                mostrarMensaje("ERROR","La tarifa no puede ser un valor negativo");
                return;
            }
        // 2. Capturar los datos de los 
        String test = txtTiempoEst.getText();
        String des = cmbDestino.getSelectedItem().toString();
        // 3. Crear el objeto Ruta y guardarlo en la lista de la empresa
        
        String respuesta = myMenu.getMyEmpresa().registrarRuta(des, test, tar);
        
        procesarRespuestaEmpresa(respuesta);

        if(respuesta.startsWith("EXITO:")){
            // 4. Limpiar los campos para la siguiente entrada
            txtTiempoEst.setText("");
            txtTarifaBase.setText("");
            llenarTablaRutas();
            cargarCombosSalidas();
        }
        

        } catch (NumberFormatException e) {
            mostrarMensaje("ERROR" ,"La tarifa debe ser un número válido.");
        } catch (Exception e) {
            mostrarMensaje("ERROR","Ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAnadirRutaActionPerformed

    private void cmdAnadirBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnadirBusActionPerformed
        try {

        // Validar campos vacíos
        if (txtPlacaBus.getText().trim().isEmpty() || comboTipoServicioBus.getSelectedItem() == null) {
            mostrarMensaje("INFO","Complete por favor todos los campos.");
            return;
        }

        String tipoServicio = comboTipoServicioBus.getSelectedItem().toString();
        String placa = txtPlacaBus.getText().trim();
        
        // Crear bus
        String resultado = myMenu.getMyEmpresa().registrarBus(placa, tipoServicio);
        
        procesarRespuestaEmpresa(resultado);

        if (resultado.startsWith("ERROR:")) {
            return;
        }
        
        llenarTablaBuses();
        cargarCombosSalidas();
        cargarCombosBuses();
        txtPlacaBus.setText("");
    } catch (Exception e) {
        mostrarMensaje("ERROR",  e.getMessage());
    }
    }//GEN-LAST:event_cmdAnadirBusActionPerformed

    private void cmdAnadirSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnadirSalidaActionPerformed
        try {
            if (txtHoraSalida.getText().trim().isEmpty()
                    || comboRutaSalida.getSelectedItem() == null
                    || comboBusSalida.getSelectedItem() == null
                    || calendarFechaSalida.getDate() == null) {

                mostrarMensaje("INFO", "Complete todos los campos de la salida.");
                return;
            }

            String codigoRuta = comboRutaSalida.getSelectedItem().toString();
            String placaBus = comboBusSalida.getSelectedItem().toString();
            String hora = normalizarHora(txtHoraSalida.getText());
            if (hora == null) {
                mostrarMensaje("ERROR", "La hora debe estar en formato 24 horas. Ejemplos: 6, 06:00, 17:30.");
                return;
            }

            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            String fecha = formatoFecha.format(calendarFechaSalida.getDate());

            String respuesta = myMenu.getMyEmpresa().registrarSalida(codigoRuta, placaBus, fecha, hora);
            procesarRespuestaEmpresa(respuesta);

            if (respuesta.startsWith("EXITO:")) {
                llenarTablaSalidas();
                txtHoraSalida.setText("");
            }
        } catch (Exception e) {
            mostrarMensaje("ERROR", "Error al crear la salida: " + e.getMessage());
        }
    }//GEN-LAST:event_cmdAnadirSalidaActionPerformed
    private void comboTipoServicioBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoServicioBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoServicioBusActionPerformed

    private void txtTiempoEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoEstActionPerformed

    private void cmbDestinoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestinoNActionPerformed
        String nuevoDestino = txtDestinoN.getText().trim();

        if (nuevoDestino.isEmpty()) {
            mostrarMensaje("INFO", "Por favor, ingrese un nombre de destino.");
            return;
        }

        String respuesta = myMenu.getMyEmpresa().registrarNuevoDestino(nuevoDestino);
        procesarRespuestaEmpresa(respuesta);

        if (respuesta.startsWith("EXITO:")) {
            cargarCombosDestinos();
            txtDestinoN.setText("");
        }
    }//GEN-LAST:event_cmbDestinoNActionPerformed
    private void cmdActualizarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarRutaActionPerformed
    try {
        if (cmbRutacg.getSelectedItem() == null || txtNuevaTarifa.getText().trim().isEmpty()) {
            mostrarMensaje("INFO", "Seleccione una ruta e ingrese la nueva tarifa.");
            return;
        }

        String codigoRuta = cmbRutacg.getSelectedItem().toString();
        double nuevaTarifa = Double.parseDouble(txtNuevaTarifa.getText().trim());

        if (nuevaTarifa < 0) {
            mostrarMensaje("ERROR", "La tarifa no puede ser un valor negativo.");
            return;
        }

        String respuesta = myMenu.getMyEmpresa().actualizarTarifaRuta(codigoRuta, nuevaTarifa);
        procesarRespuestaEmpresa(respuesta);

        if (respuesta.startsWith("EXITO:")) {
            llenarTablaRutas();
            llenarTablaSalidas();
            txtNuevaTarifa.setText("");
        }

    } catch (NumberFormatException e) {
        mostrarMensaje("ERROR", "Ingrese un valor numerico valido para la tarifa.");
    } catch (Exception e) {
        mostrarMensaje("ERROR", "Error al actualizar la ruta: " + e.getMessage());
    }
    }//GEN-LAST:event_cmdActualizarRutaActionPerformed
    private void cmbPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlacasActionPerformed
        actualizarComboEstadosSegunBus();
    }//GEN-LAST:event_cmbPlacasActionPerformed

    private void cmdActualizarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarBusActionPerformed
    try {
        if (cmbPlacas.getSelectedItem() == null || cmbNuevoEstado.getSelectedItem() == null) {
            mostrarMensaje("INFO","Por favor, seleccione una placa y un nuevo estado.");
            return;
        }
        
        String placa = cmbPlacas.getSelectedItem().toString();
        String nuevoEstado = cmbNuevoEstado.getSelectedItem().toString();
        
        // 1. Buscar el bus
        String reporteFinal = myMenu.getMyEmpresa().actualizarEstadoBus(placa, nuevoEstado);
        
        procesarRespuestaEmpresa(reporteFinal);
        
        llenarTablaBuses();       
        llenarTablaSalidas();
        cargarCombosSalidas();    
        actualizarComboEstadosSegunBus();
        //mostrarMensaje("ERROR"," No se encontró el bus seleccionado.");
    } catch (Exception e) {
        mostrarMensaje("ERROR"," al actualizar estado del bus: " + e.getMessage());
    }
    }//GEN-LAST:event_cmdActualizarBusActionPerformed

    private void cmbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDestinoActionPerformed

    private void cmbActualizarSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActualizarSalidasActionPerformed
        try {
            String respuesta = myMenu.getMyEmpresa().verificarEstadoSalidasEnTiempoReal();
            procesarRespuestaEmpresa(respuesta);
            llenarTablaBuses();
            llenarTablaSalidas();
            actualizarComboEstadosSegunBus();
        } catch (Exception e) {
            mostrarMensaje("ERROR", "No se pudieron actualizar las salidas: " + e.getMessage());
        }
    }//GEN-LAST:event_cmbActualizarSalidasActionPerformed
    private void llenarTablaRutas() {
        DefaultTableModel modelo = (DefaultTableModel) tablaRutas.getModel();
        modelo.setRowCount(0);
        
        String[][] datosRutas = myMenu.getMyEmpresa().obtenerMatrizRutas();
        
        for (String[] fila : datosRutas) {
            modelo.addRow(fila);
        }
    }
    private void llenarTablaBuses() {
        DefaultTableModel modelo = (DefaultTableModel) tablaBuses.getModel();
        modelo.setRowCount(0);

        String[][] datosBuses = myMenu.getMyEmpresa().obtenerMatrizBuses();
        
        for (String[] fila : datosBuses) {
            modelo.addRow(fila);
        }
    }
        
    private void llenarTablaSalidas() {
        DefaultTableModel modelo = (DefaultTableModel) tablaSalidas.getModel();
        modelo.setRowCount(0); 
    
        String[][] datosSalidas = myMenu.getMyEmpresa().obtenerMatrizSalidas();
        
        for (String[] fila : datosSalidas) {
            modelo.addRow(fila);
        }
    }
    private void cargarCombosBuses() {
        cmbPlacas.removeAllItems();
        comboBusSalida.removeAllItems();
        
        String[] placas = myMenu.getMyEmpresa().obtenerPlacasBuses();
        for (String placa : placas) {
            cmbPlacas.addItem(placa);
            comboBusSalida.addItem(placa);
        }
        
        comboTipoServicioBus.removeAllItems();
        comboTipoServicioBus.addItem("NORMAL");
        comboTipoServicioBus.addItem("EJECUTIVO");
        
        actualizarComboEstadosSegunBus();
    }
    
    private void actualizarComboEstadosSegunBus() {
       if (cmbPlacas.getSelectedItem() == null) return;
       
       String placaSeleccionada = cmbPlacas.getSelectedItem().toString();
       String estadoActual = myMenu.getMyEmpresa().obtenerEstadoBus(placaSeleccionada);
       
       if (!estadoActual.isBlank()) {
           cmbNuevoEstado.removeAllItems();
           
           if (estadoActual.equalsIgnoreCase("MANTENIMIENTO")) {
               cmbNuevoEstado.addItem("DISPONIBLE");
           } 
           else if (estadoActual.equalsIgnoreCase("EN_SERVICIO")) {
               cmbNuevoEstado.addItem("DISPONIBLE");
               cmbNuevoEstado.addItem("MANTENIMIENTO");
           } 
           else {
               cmbNuevoEstado.addItem("MANTENIMIENTO");
           }
       }
    }
    

    private void cargarCombosSalidas() {
        comboRutaSalida.removeAllItems();
        cmbRutacg.removeAllItems();
        
        String[] codigos = myMenu.getMyEmpresa().obtenerCodigosRutas();
        for (String codigo : codigos) {
            comboRutaSalida.addItem(codigo);
            cmbRutacg.addItem(codigo);
        }
    }
    private void cargarCombosDestinos() {
        cmbDestino.removeAllItems();
        for (String d : myMenu.getMyEmpresa().getListaDestinos()) {
            cmbDestino.addItem(d);
        }
    }
    private String normalizarHora(String textoHora) {
        String horaLimpia = textoHora.trim();

        if (horaLimpia.matches("\\d{1,2}")) {
            int hora = Integer.parseInt(horaLimpia);

            if (hora < 0 || hora > 23) {
                return null;
            }

            return String.format("%02d:00", hora);
        }

        if (horaLimpia.matches("\\d{1,2}:\\d{1,2}")) {
            String[] partes = horaLimpia.split(":");
            int hora = Integer.parseInt(partes[0]);
            int minutos = Integer.parseInt(partes[1]);

            if (hora < 0 || hora > 23 || minutos < 0 || minutos > 59) {
                return null;
            }

            return String.format("%02d:%02d", hora, minutos);
        }

        return null;
    }
    
    private void procesarRespuestaEmpresa(String respuesta) {
        String[] lineas = respuesta.split("\\R");
        for (String linea : lineas) {
            if (linea.isBlank()) {
                continue;
            }

            if (linea.startsWith("EXITO:")) {
                mostrarMensaje("EXITO", linea.replace("EXITO:", "").trim());
            } else if (linea.startsWith("ERROR:")) {
                mostrarMensaje("ERROR", linea.replace("ERROR:", "").trim());
            } else if (linea.startsWith("INFO:")) {
                mostrarMensaje("INFO", linea.replace("INFO:", "").trim());
            } else {
                mostrarMensaje("INFO", linea.trim());
            }
        }
    }
    private void mostrarMensaje(String tipo, String mensaje) {
        String prefijo = "";
    
        switch (tipo.toUpperCase()) {
            case "EXITO":
                prefijo = "[✔ ÉXITO] ";
                break;
            case "ERROR":
                prefijo = "[❌ ERROR] ";
                break;
            case "INFO":
                prefijo = "[💡 INFO] ";
                break;
            default:
                prefijo = "[> ] ";
                break;
        }
    
        txtMensajes.append(prefijo + mensaje + "\n");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAbajoSalidas;
    private javax.swing.JButton btnAnadirRuta;
    private de.wannawork.jcalendar.JCalendarComboBox calendarFechaSalida;
    private javax.swing.JButton cmbActualizarSalidas;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JButton cmbDestinoN;
    private javax.swing.JComboBox<String> cmbNuevoEstado;
    private javax.swing.JComboBox<String> cmbPlacas;
    private javax.swing.JComboBox<String> cmbRutacg;
    private javax.swing.JButton cmdActualizarBus;
    private javax.swing.JButton cmdActualizarRuta;
    private javax.swing.JButton cmdAnadirBus;
    private javax.swing.JButton cmdAnadirSalida;
    private javax.swing.JComboBox<String> comboBusSalida;
    private javax.swing.JComboBox<String> comboRutaSalida;
    private javax.swing.JComboBox<String> comboTipoServicioBus;
    private javax.swing.JLabel g;
    private javax.swing.JLabel g2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel m;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JPanel panelAbajoBuses;
    private javax.swing.JPanel panelAbajoRuta;
    private javax.swing.JPanel panelBuses;
    private javax.swing.JPanel panelFormularioRutas;
    private javax.swing.JPanel panelMensaje;
    private javax.swing.JPanel panelRutasPrincipal;
    private javax.swing.JPanel panelSalidas;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JPanel panelXBuses;
    private javax.swing.JPanel panelXRuta;
    private javax.swing.JPanel panelXSalidas;
    private javax.swing.JTable tablaBuses;
    private javax.swing.JTable tablaRutas;
    private javax.swing.JTable tablaSalidas;
    private javax.swing.JTextField txtDestinoN;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextArea txtMensajes;
    private javax.swing.JTextField txtNuevaTarifa;
    private javax.swing.JTextField txtPlacaBus;
    private javax.swing.JTextField txtTarifaBase;
    private javax.swing.JTextField txtTiempoEst;
    private javax.swing.JLabel u;
    private javax.swing.JLabel u1;
    private javax.swing.JLabel u2;
    // End of variables declaration//GEN-END:variables
}
